Добавлен проект
taratuhin/WidgetMovement pull request #1
Opened 2024-03-27 19:03 UTC by taratuhin

2024-03-27 19:17 UTC, Toxin65 commented on WidgetMovement/mainwindow.h
> +    QTimer* m_timer = nullptr;
Это лишнее. Точно.

2024-03-27 19:19 UTC, Toxin65 commented on WidgetMovement/mainwindow.cpp
> +                }
Очень странная конструкция. Можно генерировать в нужном диапазоне, и брать "большой" генератор случайных чисел.

2024-03-27 19:20 UTC, Toxin65 commented on WidgetMovement/mainwindow.cpp
> +                pb->installEventFilter(this);
Что-то лишнее.

2024-03-27 19:22 UTC, Toxin65 commented on WidgetMovement/mainwindow.cpp
> +                });
При правильно построеном владении это не нужно.

2024-03-27 19:22 UTC, Toxin65 commented on WidgetMovement/mainwindow.cpp
> +                tm->setInterval(qrand() % 100 + 50);
https://doc.qt.io/qt-6/qrandomgenerator.html#bounded-2

2024-03-27 19:23 UTC, Toxin65 commented on WidgetMovement/mainwindow.cpp
> +    qsrand(QDateTime::currentMSecsSinceEpoch() / 1000);
Это лишнее всё, есть глобальный генератор.

2024-03-27 19:23 UTC, Toxin65 commented on WidgetMovement/mainwindow.cpp
> +    m_timer->deleteLater();
Если есть владение -- это не нужно.

2024-03-27 19:24 UTC, Toxin65 requested changes
Вы не понимаете как работают деревья владения.
И ещё куча замечаний.
Исправляйте. Вопросы -- пишите, можно в ЛС.

2024-03-27 19:33 UTC, taratuhin commented on WidgetMovement/mainwindow.h
> +    QTimer* m_timer = nullptr;
Что именно лишнее (строки с 15 по 18 были в шаблоне)?

2024-03-27 19:38 UTC, Toxin65 commented on WidgetMovement/mainwindow.h
> +    QTimer* m_timer = nullptr;
Хранение указателя на таймер не нужно.

2024-03-27 20:21 UTC, taratuhin commented on WidgetMovement/mainwindow.cpp
> +    qsrand(QDateTime::currentMSecsSinceEpoch() / 1000);
qsrand(QDateTime::currentMSecsSinceEpoch() / 1000); убрал, но остальное осталось (размер экрана и создание таймера, не понимаю как можно таймер заменить глобальным генератором https://doc.qt.io/qt-6/qrandomgenerator.html#global)

2024-03-28 05:08 UTC, taratuhin commented on WidgetMovement/mainwindow.cpp
> +    qsrand(QDateTime::currentMSecsSinceEpoch() / 1000);
m_timer нужно (можно) заменить на QTimer::singleShot?

2024-03-28 08:11 UTC, Toxin65 commented on WidgetMovement/mainwindow.cpp
> +    qsrand(QDateTime::currentMSecsSinceEpoch() / 1000);
Нет, таймер нужен. Менять его на singleShot не надо. Комментарий был про одну строку.

2024-03-28 08:12 UTC, Toxin65 commented on WidgetMovement/mainwindow.h
> +    QTimer* m_timer = nullptr;
Ну если он есть, то пусть будет...

2024-03-28 08:13 UTC, Toxin65 commented on WidgetMovement/mainwindow.cpp
> +                });
Лямбда не нужна, обращение в `deleteLater` как в простой слот.

2024-03-28 08:14 UTC, Toxin65 commented on WidgetMovement/mainwindow.cpp
> +                                pb->deleteLater();
А почему два `deleteLater`?

2024-03-28 08:15 UTC, Toxin65 commented on WidgetMovement/mainwindow.cpp
> +                auto x = QRandomGenerator::global()->bounded(this->width() - pb->width());
const

2024-03-28 08:17 UTC, Toxin65 commented on WidgetMovement/mainwindow.cpp
> +                            pb->move(pb->pos() + QPoint(0, 1));
Не соответствует ТЗ. Нет реакции на наличие мыши над кнопкой.

2024-03-28 08:19 UTC, Toxin65 commented on WidgetMovement/mainwindow.cpp
> +bool MainWindow::eventFilter(QObject *obj, QEvent *event)
Не соответствует условию ТЗ `- Запрещается создавать свои классы, наследовать, переопределять методы.`

2024-03-28 08:20 UTC, Toxin65 requested changes
Нарушение условия ТЗ, некоторые ошибки.

2024-03-28 08:59 UTC, taratuhin commented on WidgetMovement/mainwindow.cpp
> +                            pb->move(pb->pos() + QPoint(0, 1));
Какой пункт в ТЗ?

2024-03-28 14:11 UTC, Toxin65 commented on WidgetMovement/mainwindow.cpp
> +                            pb->move(pb->pos() + QPoint(0, 1));
На самом деле сделано было через `MainWindow::eventFilter`, но когда я это читал, то ещё не понимал что так сделано.
Условие про то, что кнопка ускоряется, если над ней мышка.

2024-03-29 17:57 UTC, Toxin65 commented on WidgetMovement/mainwindow.cpp
> +                                tm->setInterval(interval);
Таймер будет не в восторге, что его дёргают. Предлагаю удваивать перемещение, а не таймер передёргивать.
Если подумать что делается на уровне операционной системы -- скорее всего таймер пересоздаётся.

2024-03-29 18:00 UTC, Toxin65 approved these changes
В целом то, что нужно, за исключением комментария про таймер.
Ну и прикидывайте частоту обновления кадров на экране и периоды вашего таймера, если по взрослому думать.

2024-04-13 18:31 UTC, merged